export const breadcrumbLabels = {
  trainings: "Mes formations",
  "create-session": "Créer une séssion",
  "create-training": "Créer une formation",
  sessions: "Mes séssions",
  favorites: "Favoris",
  followed: "Sessions suivies",
  created: "Créées",
  edit: "Modifier",
  create: "Créer",
  reviews: "Avis",
  participants: "Participants",
  profile: "Profil",
  settings: "Paramètres",
  notifications: "Notifications",
  help: "Aide",
};
